name: Junior Web Update


on:
  workflow_dispatch:

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch 5k.html
        run: |
          curl -o index.html https://raw.githubusercontent.com/ALD-Models/pr-tourist-map/main/5k.html

      - name: Update junior.html
        run: |
          # Uncheck the 5k checkbox
          sed -i 's/<input type="checkbox" id="fiveKCheckbox" checked>/<input type="checkbox" id="fiveKCheckbox">/g' index.html

          # Check the juniorCheckbox
          sed -i 's/<input type="checkbox" id="juniorCheckbox"/<input type="checkbox" id="juniorCheckbox" checked/g' index.html

          # Save the modified file as junior.html
          cp index.html junior.html

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add junior.html
          git commit -m 'Create junior.html with 5k markers unchecked'
          git push
