name: Update parkrun Data

on:
  workflow_dispatch:  # Allows manual execution only

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests html-table-extractor

      - name: Run parkrun data script
        run: python scripts/cancellationsv2.py
